global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'causal-ui-gym'
    environment: 'development'

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Causal UI Gym frontend metrics
  - job_name: 'causal-ui-frontend'
    static_configs:
      - targets: ['host.docker.internal:5173']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # JAX backend metrics (when available)
  - job_name: 'jax-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 30s

  # Application-specific metrics
  - job_name: 'causal-metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/causal/metrics'
    scrape_interval: 10s
    honor_labels: true
    params:
      format: ['prometheus']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Remote write configuration (for production)
# remote_write:
#   - url: 'https://prometheus-remote-write-endpoint'
#     basic_auth:
#       username: 'user'
#       password: 'password'