version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - python_packages:/usr/local/lib/python3.11/site-packages
    environment:
      - NODE_ENV=development
      - PYTHON_ENV=development
      - VITE_API_URL=http://backend:8000
      - DATABASE_URL=postgresql://user:password@postgres:5432/causal_ui_gym
      - REDIS_URL=redis://redis:6379
      - JAX_PLATFORM_NAME=cpu
      # Development API keys (use test keys or leave empty)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    networks:
      - causal-ui-network
    command: sleep infinity
    user: vscode

volumes:
  node_modules:
  python_packages: